# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false
      - name: Install and Build 🔧 # This example project is built using npm and outputs the result to the 'build' folder. Replace with the commands required to build your project, or remove this step entirely if your site is pre-built.
        run: |
          npm config set registry https://registry.npm.taobao.org
          npm install
          npm run build
      - name: Deploy
        run: |
          git config --global user.name 'luffyZh'
          git config --global user.email 'zhoudeyou945@126.com'
          git remote set-url origin https://luffyZh:${{ secrets.ACCESS_TOKEN }}@github.com/luffyZh/github-actions-demo
          npm run deploy
