# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm config set registry https://registry.npm.taobao.org
    - run: npm install
    - run: npm run build --if-present
    - run: git config --global user.email "zhoudeyou945@126.com"
    - run: git config --global user.name "luffyZh"
    - run: git remote set-url origin https://luffyZh:6a0ba252eed80421132bc4befa11dd376c0ebbaa@github.com/luffyZh/github-actions-demo
    - run: npm run deploy
      env:
        CI: true
